database:
    type: http
    serverUrl: http://zoo.studio.ml
    apiKey: AIzaSyCLQbp5X2B4SWzBw-sz9rUnGHNSdMl0Yx8
    authDomain: "studio-ed756.firebaseapp.com"
    projectId: "studio-ed756"
    guest: true


queue: local

saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
verbose: debug


